# Jalankan playbook pc-router terlebih dahulu
# Atau langsung gunakan jika anda hanya butuh playbook iptables saja
# Yaml Code by Bagas Maulana
---
- name: Iptables playbook - Block Internet Access
  become: yes
  hosts: target
  vars_prompt:
    - name: source_address
      prompt: "Masukkan source address "
      private: no

    - name: wan_interface
      prompt: "Masukkan interface wan (Ke arah public) "
  tasks:
    - name: TENTANG CREATOR
      ansible.builtin.pause:
        prompt: "This Playbook Created by analuaM sagaB | Universitas Bani Saleh |"
        seconds: 5

    - name: DISCLAIMER DARI CREATOR
      ansible.builtin.pause:
        prompt: "SCRIPT INI 97% DIBUAT TANPA AI. AI HANYA DIGUNAKAN UNTUK MEMBANTU MENJELASKAN DOKUMENTASI DARI MODULE ANSIBLE"
        seconds: 10

    - name: Update repository
      apt:
        update_cache: yes
      ignore_errors: yes

    - name: Install iptables
      apt:
        name: iptables
        state: present
      ignore_errors: yes
    
    - name: Running iptables rule | Block Internet Access
      ansible.builtin.iptables:
        chain: FORWARD
        source: "{{ source_address }}"
        out_interface: "{{ wan_interface }}"
        jump: DROP